### ISSUE TITLE
ImportError - const from constants

### ISSUE THREAD

**Issue by salitchakma** [dargueso/EHF#2]
Hi,
I am getting following ImportError, "cannot import name 'const' from 'constants'" when I run from compute_EHFheatwaves import compute_EHF in jupyter notebook. 
Thanks

**Comment by dargueso** [comment]
Hi, not sure how you're running the code, but the constants file is in the repository. You just need to run from the same place where the repository is, or alternatively, add that path to PYTHONPATH.

**Comment by salitchakma** [comment]
Hi,

Thanks. Python was importing the [constants](https://pypi.org/project/constants/) package. Thanks again!
